<?php
/**
 * Handles adding and inserting MarketPress short codes from within the tinymce editor
 *
 * @since 3.0
 * @package MarketPress
 */
add_action( 'wp_ajax_mp_shortcode_builder_search_products', array( 'MP_Shortcode_Builder', 'search_products' ) );

class MP_Shortcode_Builder {

	/**
	 * Refers to a single instance of the class.
	 *
	 * @since 3.0
	 * @access private
	 * @var object
	 */
	private static $_instance = null;

	/**
	 * Refers to the product categories
	 *
	 * @since 3.0
	 * @access public
	 * @var array
	 */
	protected $_product_cats = array();

	/**
	 * Refers to the product tags
	 *
	 * @since 3.0
	 * @access public
	 * @var array
	 */
	protected $_product_tags = array();

	/**
	 * Gets the single instance of the class.
	 *
	 * @since 3.0
	 * @access public
	 * @return object
	 */
	public static function get_instance() {
		if ( is_null( self::$_instance ) ) {
			self::$_instance = new MP_Shortcode_Builder();
		}
		return self::$_instance;
	}

	/**
	 * Searches posts
	 *
	 * @since 1.0
	 * @access public
	 * @action wp_ajax_mp_shortcode_builder_search_posts
	 */
	public static function search_products() {
		add_filter( 'posts_search', array( __CLASS__, 'search_by_title_only' ), 500, 2 );

		$query	 = new WP_Query( array(
			'paged'					 => isset( $_GET[ 'page' ] ) ? $_GET[ 'page' ] : false,
			'posts_per_page'		 => -1,
			's'						 => isset( $_GET[ 'search_term' ] ) ? $_GET[ 'search_term' ] : false,
			'update_post_meta_cache' => false,
			'update_post_term_cache' => false,
			'orderby'				 => 'title',
			'order'					 => 'ASC',
			'post_type'				 => MP_Product::get_post_type(),
		) );
		$data	 = array( 'posts' => array(), 'posts_per_page' => isset( $args[ 'posts_per_page' ] ) ? $args[ 'posts_per_page' ] : '-1', 'total' => $query->found_posts );

		while ( $query->have_posts() ) : $query->the_post();
			$data[ 'posts' ][] = array( 'id' => get_the_ID(), 'text' => get_the_title() );
		endwhile;

		wp_send_json( $data );
	}

	/**
	 * Search by title only
	 *
	 * @since 3.0
	 * @access public
	 * @filter posts_search
	 * @param string $search
	 * @param object $wp_query
	 * @return string
	 */
	public static function search_by_title_only( $search, &$wp_query ) {
		global $wpdb;

		if ( empty( $search ) ) {
			return $search; // skip processing - no search term in query
		}

		$q			 = $wp_query->query_vars;
		$n			 = !empty( $q[ 'exact' ] ) ? '' : '%';
		$search		 = '';
		$searchand	 = '';

		foreach ( (array) $q[ 'search_terms' ] as $term ) {
			$term		 = esc_sql( $wpdb->esc_like( $term ) );
			$search .= "{$searchand}($wpdb->posts.post_title LIKE '{$n}{$term}{$n}')";
			$searchand	 = ' AND ';
		}

		if ( !empty( $search ) ) {
			$search = " AND ({$search}) ";
			if ( !is_user_logged_in() ) {
				$search .= " AND ($wpdb->posts.post_password = '') ";
			}
		}

		return $search;
	}

	/**
	 * Constructor.
	 *
	 * @since 3.0
	 * @access private
	 */
	private function __construct() {
		$this->_product_cats = get_terms( 'product_category', 'hide_empty=0' );
		$this->_product_tags = get_terms( 'product_tag', 'hide_empty=0' );

		if ( is_admin() && ! is_customize_preview() ) {
			add_action( 'media_buttons', array( &$this, 'media_buttons' ) );
		}

		add_action( 'admin_enqueue_scripts', array( &$this, 'enqueue_styles_scripts' ) );
		add_action( 'in_admin_footer', array( &$this, 'display_short_code_form' ) );
		add_filter( 'wp_dropdown_cats', array( &$this, 'wp_dropdown_cats' ), 10, 2 );
	}

	/**
	 * Add data-default attribute to html generated by wp_dropdown_categories() function
	 *
	 * @since 3.0
	 * @access public
	 * @filter wp_dropdown_cats
	 * @return string
	 */
	public function wp_dropdown_cats( $html, $args ) {
		return str_replace( '<select ', '<select data-default="-1" ', $html );
	}

	/**
	 * Displays the short code form
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_short_code_form() {
		if ( did_action( 'media_buttons' ) == 0 ) {
			// Only continue if a tinymce editor exists on the current page
			return;
		}

		if ( ! function_exists( 'is_plugin_active_for_network' ) ) {
			require_once( ABSPATH . '/wp-admin/includes/plugin.php' );
		}

		if ( ! function_exists( 'mp_get_plugin_slug' ) ) {
			function mp_get_plugin_slug() {
				if ( file_exists( dirname( __FILE__ ) . '/includes/psource-plugin-update/psource-info.php' ) ) {
					return 'marketpress/marketpress.php';
				} else {
					return 'marketpress/marketpress.php';
				}
			}
		}

		$shortcodes = array(
			'mp_tag_cloud'			 => __( 'Zeige eine Cloud oder eine Liste Deiner Produkt-Tags an.', 'mp' ),
			'mp_list_categories'	 => __( 'Zeige eine HTML-Liste Deiner Produktkategorien an.', 'mp' ),
			'mp_dropdown_categories' => __( 'Zeige eine HTML-Dropdown-Liste Deiner Produktkategorien an.', 'mp' ),
			'mp_featured_products'	 => __( 'Zeige eine Liste der vorgestellten Produkte an.', 'mp' ),
			'mp_popular_products'	 => __( 'Zeige eine Liste der beliebtesten Produkte an, die nach Verkäufen sortiert sind.', 'mp' ),
			'mp_related_products'	 => __( 'Zeige Produkte an, die sich auf das angezeigte beziehen.', 'mp' ),
			'mp_list_products'		 => __( 'Zeige eine Liste der Produkte nach Wünschen an.', 'mp' ),
			'mp_product'			 => __( 'Zeige ein einzelnes Produkt an.', 'mp' ),
			'mp_product_image'		 => __( 'Zeige das abgebildete Bild eines bestimmten Produktes an.', 'mp' ),
			'mp_buy_button'			 => __( 'Zeige die Schaltfläche Kaufen oder In den Warenkorb.', 'mp' ),
			'mp_product_price'		 => __( 'Zeige Produktpreis (und Angebotspreis anzeigen).', 'mp' ),
			'mp_product_sku'		 => __( 'Zeige die Produkt-SKU-Nummer(n) an..', 'mp' ),
			'mp_product_stock'		 => __( 'Zeige aktuellen Produktbestand.', 'mp' ),
			'mp_product_meta'		 => __( 'Zeige die vollständige Produkt-Meta-Box mit dem Preis an und kaufe jetzt/füge dem Warenkorb hinzu.', 'mp' ),
			'mp_cart_widget'		 => __( 'Zeige das Warenkorb-Widget an.', 'mp' ),
			'mp_cart_link'			 => __( 'Zeige einen Link oder eine URL zur aktuellen Warenkorbseite an.', 'mp' ),
			'mp_store_link'			 => __( 'Zeige einen Link oder eine URL zur aktuellen Shop-Seite an.', 'mp' ),
			'mp_products_link'		 => __( 'Zeige einen Link oder eine URL zur aktuellen Produktlistenseite an.', 'mp' ),
			'mp_orderstatus_link'	 => __( 'Zeige einen Link oder eine URL zur Bestellstatusseite an.', 'mp' ),
			'mp_store_navigation'	 => __( 'Zeige eine Liste mit Links zu Deinen Geschäftsseiten an.', 'mp' ),
		);

		if ( is_multisite() && is_plugin_active_for_network( mp_get_plugin_slug() ) ) {
			$settings = get_site_option( 'mp_network_settings', array() );
			if ( ( isset($settings['main_blog']) && mp_is_main_site() ) || isset($settings['main_blog']) && !$settings['main_blog'] ) {
				$mu_shortcodes = array(
					'mp_list_global_products'	  => __( 'Zeige eine Liste oder ein Raster Deiner globalen Produkte an.', 'mp' ),
					'mp_global_categories_list'   => __( 'Zeige eine Liste Deiner globalen Kategorien an.', 'mp' ),
					'mp_global_tag_cloud'		  => __( 'Zeige eine Cloud oder Liste Deiner globalen Produkt-Tags an.', 'mp' ),
				);

				$shortcodes = array_merge($shortcodes, $mu_shortcodes);
			}
		}

		?>
		<div id="mp-shortcode-builder" style="display:none">
			<form id="mp-shortcode-builder-form">
				<h3><?php _e( 'E-Commerce-Shortcode hinzufügen', 'mp' ); ?></h3>
				<strong><?php _e( 'Was würdest du gern tun?', 'mp' ); ?></strong><br />
				<select name="shortcode">
					<option value=""><?php _e( 'Wähle eine Aktion aus', 'mp' ); ?></option>
					<?php foreach ( $shortcodes as $shortcode => $label ) : ?>
						<option value="<?php echo esc_attr( $shortcode ); ?>"><?php echo '[' . $shortcode . '] ' . $label; ?></option>
					<?php endforeach; ?>
				</select>

				<div class="shortcode-attributes">
					<h2><?php _e( 'Attribute', 'mp' ); ?></h2>
					<?php
					foreach ( $shortcodes as $shortcode => $label ) {
						$func = 'display_' . $shortcode . '_attributes';

						if ( method_exists( $this, $func ) ) {
							call_user_func( array( &$this, $func ) );
						}
					}
					?>
				</div>
				<?php $this->display_shortcode_builder_form_buttons(); ?>
			</form>
		</div>
		<?php
	}

	/**
	 * Displays the [mp_list_categories] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_list_categories_attributes() {
		?>
		<table id="mp-list-categories-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wenn ein Wert eingegeben wird, wird ein Link zu allen Kategorien angezeigt, wenn der Stil auf Liste gesetzt ist.', 'mp' ); ?></span></span> Option alle anzeigen</th>
				<td>
					<input type="text" name="show_option_all" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortiere Kategorien alphabetisch, nach eindeutiger Kategorie-ID oder nach der Anzahl der Beiträge in dieser Kategorie.', 'mp' ); ?></span></span> Sortieren nach</th>
				<td>
					<select name="orderby" data-default="name">
						<?php foreach ( array( 'ID', 'name', 'slug', 'count', 'term_group' ) as $value ) : ?>
							<option <?php selected( $value, 'name' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge für Kategorien (entweder aufsteigend oder absteigend).', 'mp' ); ?></span></span> Sortieren</th>
				<td>
					<select name="order" data-default="ASC">
						<?php foreach ( array( 'ASC', 'DESC' ) as $value ) : ?>
							<option <?php selected( $value, 'ASC' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Stil zum Anzeigen der Kategorieliste. Ein Wert der Liste zeigt die Kategorien als Listenelemente an, während keines keine spezielle Anzeigemethode generiert (die Listenelemente werden durch <br> Tags getrennt).', 'mp' ); ?></span></span> Stil</th>
				<td>
					<select name="style" data-default="list">
						<?php foreach ( array( 'list', 'none' ) as $value ) : ?>
							<option <?php selected( $value, 'list' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige der aktuellen Anzahl von Posts in jeder Kategorie um.', 'mp' ); ?></span></span> Anzahl anzeigen</th>
				<td>
					<input type="checkbox" name="show_count" data-default="" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige von Kategorien ohne Beiträge um.', 'mp' ); ?></span></span> Leere ausblenden</th>
				<td>
					<input type="checkbox" name="hide_empty" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt fest, ob die Beschreibung einer Kategorie in das title-Attribut der erstellten Links eingefügt wird (z.B. &lt;a title="&lt;em&gt;Category Description&lt;/em&gt;" href="...).', 'mp' ); ?></span></span> Beschreibung als Titel</th>
				<td>
					<input type="checkbox" name="use_desc_for_title" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeige nur Kategorien an, die untergeordnete Elemente der durch diesen Parameter angegebenen Kategorie sind.', 'mp' ); ?></span></span> Kind von</th>
				<td>
					<?php
					wp_dropdown_categories( array(
						'taxonomy'			 => 'product_category',
						'hide_empty'		 => 0,
						'show_option_none'	 => __( 'Alle', 'mp' ),
						'name'				 => 'child_of',
					) );
					?>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeige einen Link zum RSS-2-Feed jeder Kategorie an und lege den anzuzeigenden Linktext fest. Die Standardeinstellung ist, dass kein Text und kein Feed angezeigt wird.', 'mp' ); ?></span></span> Feed</th>
				<td>
					<input type="text" name="feed" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row">feed_type</th>
				<td>
					<input type="text" name="feed_type" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Lege einen URI für ein Bild fest (normalerweise ein RSS-Feed-Symbol), der als Link zu den einzelnen RSS-2-Feeds der Kategorie dient. Dieser Parameter überschreibt den Feed-Parameter. Für diesen Parameter gibt es keine Standardeinstellung.', 'mp' ); ?></span></span> Feed-Bild</th>
				<td>
					<input type="text" name="feed_image" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schließe eine oder mehrere Kategorien von den Ergebnissen aus. Der Parameter include muss leer sein.', 'mp' ); ?></span></span> Ausschließen</th>
				<td>
					<select name="exclude" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorie wählen', 'mp' ); ?>" multiple>
						<?php
						foreach ( $this->_product_cats as $cat ) {
							if ( isset( $cat ) ) {
								?>
								<option value="<?php echo esc_attr( isset( $cat->term_id ) ? $cat->term_id : ''  ); ?>"><?php echo isset( $cat->name ) ? $cat->name : ''; ?></option>
								<?php
							}
						}
						?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schließe nur diese Kategorien ein.', 'mp' ); ?></span></span> Einschließen</th>
				<td>
					<select name="include" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorie wählen', 'mp' ); ?>" multiple>
						<?php
						foreach ( $this->_product_cats as $cat ) :
							if ( isset( $cat ) ) {
								?>
								<option value="<?php echo esc_attr( isset( $cat->term_id ) ? $cat->term_id : ''  ); ?>"><?php echo isset( $cat->name ) ? $cat->name : ''; ?></option>
							<?php }endforeach;
						?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Kategoriebaum von den Ergebnissen ausschließen. Der Parameter include muss leer sein. Wenn der hierarchische Parameter true ist, verwende exclude anstelle von exclude_tree.', 'mp' ); ?></span></span> Baum ausschließen</th>
				<td>
					<select name="exclude_tree" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorie wählen', 'mp' ); ?>" multiple>
						<?php foreach ( $this->_product_cats as $cat ) : ?>
							<option value="<?php echo esc_attr( isset( $cat->term_id ) ? $cat->term_id : ''  ); ?>"><?php echo isset( $cat->name ) ? $cat->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeige Unterkategorien als innere Listenelemente (unter dem übergeordneten Listenelement) oder inline an.', 'mp' ); ?></span></span> Hierarchisch</th>
				<td>
					<input type="checkbox" name="hierarchical" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Lege den Titel und den Stil des äußeren Listenelements fest. Wenn vorhanden, aber leer, wird das äußere Listenelement nicht angezeigt.', 'mp' ); ?></span></span> Titel-Liste</th>
				<td>
					<input type="text" name="title_li" data-default="Categories" value="Categories" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Stelle den Text so ein, dass angezeigt wird, wenn keine Kategorien aufgelistet sind.', 'mp' ); ?></span></span> Option anzeigen Keine</th>
				<td>
					<input type="text" name="show_option_none" data-default="Keine Kategorien" value="Keine Kategorien" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt die Anzahl der anzuzeigenden Kategorien fest. Dadurch wird der SQL LIMIT-Wert definiert.', 'mp' ); ?></span></span> Anzahl</th>
				<td>
					<input type="text" name="number" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Dieser Parameter steuert, wie viele Ebenen in der Hierarchie der Kategorien in die Liste der Kategorien aufgenommen werden sollen. HINWEIS: Das standardmäßig deaktivierte "hierarchische" Argument überschreibt das Tiefenargument, sofern es nicht wahr ist. Wenn das Argument falsch ist, werden alle Kategorien angezeigt. Wenn es aktiviert ist, wird der Wert im Argument "Tiefe" verwendet.', 'mp' ); ?></span></span> Tiefe</th>
				<td>
					<input type="text" name="depth" data-default="0" value="0" />
					<ul>
						<li><code>0</code> - <?php _e( 'Alle Kategorien und untergeordneten Kategorien (Standard).', 'mp' ); ?></li>
						<li><code>-1</code> - <?php _e( 'Alle Kategorien werden in flacher Form (ohne Einzug) angezeigt (überschreibt hierarchisch).', 'mp' ); ?></li>
						<li><code>1</code> - <?php _e( 'Nur Kategorien der obersten Ebene anzeigen.', 'mp' ); ?></li>
						<li><code>n</code> - <?php _e( 'Der Wert von n (eine Zahl) gibt die Tiefe (oder Ebene) an, die bei der Anzeige von Kategorien herabgesetzt werden soll.', 'mp' ); ?></li>
					</ul>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Berechnet die Anzahl der Links oder Posts, indem Elemente aus untergeordneten Kategorien einbezogen werden. Wenn show_counts und hierarchical true sind, wird dies automatisch auf true gesetzt.', 'mp' ); ?></span></span> Pad Zähler</th>
				<td>
					<input type="checkbox" name="pad_counts" data-default="0" value="1" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_dropdown_categories] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_dropdown_categories_attributes() {
		?>
		<table id="mp-dropdown-categories-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wenn ein Wert eingegeben wird, wird ein Link zu allen Kategorien angezeigt, wenn der Stil auf Liste gesetzt ist.', 'mp' ); ?></span></span> Option alle anzeigen</th>
				<td>
					<input type="text" name="show_option_all" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortiere Kategorien alphabetisch, nach eindeutiger Kategorie-ID oder nach der Anzahl der Beiträge in dieser Kategorie.', 'mp' ); ?></span></span> Sortieren nach</th>
				<td>
					<select name="orderby" data-default="name">
						<?php foreach ( array( 'ID', 'name', 'slug', 'count', 'term_group' ) as $value ) : ?>
							<option <?php selected( $value, 'name' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge für Kategorien (entweder aufsteigend oder absteigend).', 'mp' ); ?></span></span> Sortieren</th>
				<td>
					<select name="order" data-default="ASC">
						<?php foreach ( array( 'ASC', 'DESC' ) as $value ) : ?>
							<option <?php selected( $value, 'ASC' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<!--<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php /*_e( 'Style to display the categories list in. A value of list displays the categories as list items while none generates no special display method (the list items are separated by <br> tags).', 'mp' ); */?></span></span> Stil</th>
				<td>
					<select name="style" data-default="list">
						<?php /*foreach ( array( 'list', 'none' ) as $value ) : */?>
							<option <?php /*selected( $value, 'list' ); */?>><?php /*echo $value; */?></option>
						<?php /*endforeach; */?>
					</select>
				</td>
			</tr>-->
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige der aktuellen Anzahl von Posts in jeder Kategorie um.', 'mp' ); ?></span></span> Anzahl anzeigen</th>
				<td>
					<input type="checkbox" name="show_count" data-default="" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige von Kategorien ohne Beiträge um.', 'mp' ); ?></span></span> Leere ausblenden</th>
				<td>
					<input type="checkbox" name="hide_empty" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeige nur Kategorien an, die untergeordnete Elemente der durch diesen Parameter angegebenen Kategorie sind.', 'mp' ); ?></span></span>  Kind von</th>
				<td>
					<?php
					wp_dropdown_categories( array(
						'taxonomy'			 => 'product_category',
						'hide_empty'		 => 0,
						'show_option_none'	 => __( 'Alle', 'mp' ),
						'name'				 => 'child_of',
					) );
					?>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schließe eine oder mehrere Kategorien von den Ergebnissen aus. Der Parameter include muss leer sein.', 'mp' ); ?></span></span> Ausschließen</th>
				<td>
					<select name="exclude" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorie wählen', 'mp' ); ?>" multiple>
						<?php
						$cats = get_categories( array(
							'hide_empty' => 0,
							'taxonomy'	 => 'product_category'
						) );

						foreach ( $cats as $cat ) :
							?>
							<option value="<?php echo esc_attr( $cat->term_id ); ?>"><?php echo $cat->name; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Kategoriebaum von den Ergebnissen ausschließen. Der Parameter include muss leer sein. Wenn der hierarchische Parameter true ist, verwende exclude anstelle von exclude_tree.', 'mp' ); ?></span></span> Baum ausschließen</th>
				<td>
					<select name="exclude_tree" class="mp-chosen-select" data-placeholder="<?php _e( 'Kategorie wählen', 'mp' ); ?>" multiple>
						<?php
						$cats = get_categories( array(
							'hide_empty' => 0,
							'taxonomy'	 => 'product_category'
						) );

						foreach ( $cats as $cat ) :
							?>
							<option value="<?php echo esc_attr( $cat->term_id ); ?>"><?php echo $cat->name; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Zeige Unterkategorien als innere Listenelemente (unter dem übergeordneten Listenelement) oder inline an.', 'mp' ); ?></span></span> Hierarchisch</th>
				<td>
					<input type="checkbox" name="hierarchical" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Stelle den Text so ein, dass angezeigt wird, wenn keine Kategorien aufgelistet sind.', 'mp' ); ?></span></span> Option anzeigen Keine</th>
				<td>
					<input type="text" name="show_option_none" data-default="<?php echo esc_attr( __( 'Keine Kategorien', 'mp' ) ); ?>" value="<?php echo esc_attr( __( 'Keine Kategorien', 'mp' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die maximale Tiefe. Dies wird ignoriert, es sei denn, hierarchisch ist auf true gesetzt.', 'mp' ); ?></span></span> Tiefe</th>
				<td>
					<input type="text" name="depth" data-default="0" value="0" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Berechnet die Anzahl der Links oder Posts, indem Elemente aus untergeordneten Kategorien einbezogen werden. Wenn show_counts und hierarchical true sind, wird dies automatisch auf true gesetzt.', 'mp' ); ?></span></span> Pad Zähler</th>
				<td>
					<input type="checkbox" name="pad_counts" data-default="0" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welche Kategorie-ID ist ausgewählt.', 'mp' ); ?></span></span> Ausgewählt</th>
				<td>
					<input type="text" name="selected" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Attributwert "id" für das ausgewählte Element. ', 'mp' ); ?></span></span> ID</th>
				<td>
					<input type="text" name="id" data-default="0" value="0" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Attributwert "Name" für das ausgewählte Element. ', 'mp' ); ?></span></span> Name</th>
				<td>
					<input type="text" name="name" data-default="cat" value="cat" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Attributwert "tabindex" für das ausgewählte Element. ', 'mp' ); ?></span></span>  Tab-Index</th>
				<td>
					<input type="text" name="tab_index" data-default="0" value="0" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_tag_cloud] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_tag_cloud_attributes() {
		?>
		<table id="mp-tag-cloud-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Textgröße des Tags mit dem kleinsten Zählwert (Einheiten, angegeben durch den Einheitenparameter).', 'mp' ); ?></span></span> Kleinste</th>
				<td>
					<input type="text" name="smallest" data-default="8" value="8" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Textgröße des Tags mit dem größten Zählwert (Einheiten, angegeben durch den Einheitenparameter).', 'mp' ); ?></span></span> Größte</th>
				<td>
					<input type="text" name="largest" data-default="22" value="22" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Maßeinheit für die kleinsten und größten Werte. Dies kann ein beliebiger CSS-Längenwert sein, z.B. pt, px, em, %.', 'mp' ); ?></span></span> Einheit</th>
				<td>
					<input type="text" name="unit" data-default="pt" value="pt" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Anzahl der tatsächlichen Tags, die in der Cloud angezeigt werden sollen. (Verwenden Sie "0", um alle Tags anzuzeigen.)', 'mp' ); ?></span></span> Anzahl</th>
				<td>
					<input type="text" name="number" data-default="45" value="45" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Format der Cloud-Anzeige.', 'mp' ); ?></span></span> Format</th>
				<td>
					<label for="mp-tag-cloud-format-flat"><input type="radio" name="format" id="mp-tag-cloud-format-flat" data-default="flat" value="flat" checked /> <?php _e( 'getrennt durch Leerzeichen, definiert durch den Parameter "separator".', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-format-list"><input type="radio" name="format" id="mp-tag-cloud-format-list" data-default="flat" value="list" /> <?php _e( 'UL mit einer Klasse von "wp-tag-cloud"', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text/Leerzeichen zwischen Tags', 'mp' ); ?></span></span> Trennzeichen</th>
				<td>
					<input type="text" name="separator" data-default="\n" value="\n" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Reihenfolge der Tags.', 'mp' ); ?></span></span> Sortieren nach</th>
				<td>
					<label for="mp-tag-cloud-orderby-name"><input type="radio" name="orderby" id="mp-tag-cloud-orderby-name" data-default="name" value="name" checked /> <?php _e( 'Name', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-orderby-count"><input type="radio" name="orderby" id="mp-tag-cloud-orderby-count" data-default="count" value="count" /> <?php _e( 'Anzahl', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge.', 'mp' ); ?></span></span> Sortieren</th>
				<td>
					<label for="mp-tag-cloud-order-asc"><input type="radio" name="order" id="mp-tag-cloud-order-asc" data-default="ASC" value="ASC" checked /> <?php _e( 'Aufsteigend', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-order-desc"><input type="radio" name="order" id="mp-tag-cloud-order-desc" data-default="ASC" value="DESC" /> <?php _e( 'Absteigend', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-order-rand"><input type="radio" name="order" id="mp-tag-cloud-order-rand" data-default="RAND" value="RAND" /> <?php _e( 'Zufällig', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Durch Kommas getrennte Liste der auszuschließenden Tags (term_id). Beispiel: exclude = 5,27 bedeutet, dass Tags mit der term_id 5 oder 27 NICHT angezeigt werden. Standardmäßig wird nichts ausgeschlossen.', 'mp' ); ?></span></span> Ausschließen</th>
				<td>
					<input type="text" name="exclude" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Durch Kommas getrennte Liste der einzuschließenden Tags (term_id). Include = 5,27 bedeutet beispielsweise, dass nur Tags mit der term_id 5 oder 27 angezeigt werden. Standardmäßig wird alles eingeschlossen.', 'mp' ); ?></span></span> Einschließen</th>
				<td>
					<input type="text" name="include" data-default="" value="" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_featured_products] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_featured_products_attributes() {
		?>
		<table id="mp-featured-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob die Produktliste paginiert werden soll. Dies ist nützlich, um nur eine Teilmenge anzuzeigen.', 'mp' ); ?></span></span> Paginieren</th>
				<td>
					<input type="checkbox" name="paginate" data-default="<?php echo esc_attr( mp_get_setting( 'paginate' ) ); ?>" value="1" <?php checked( 1, mp_get_setting( 'paginate' ) ); ?> />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Seitenzahl, die in der Produktliste angezeigt werden soll, wenn "paginieren" auf "wahr" gesetzt ist.', 'mp' ); ?></span></span> Seite</th>
				<td>
					<input type="text" name="page" data-default="1" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele Produkte sollen in der Produktliste angezeigt werden, wenn "paginieren" auf "wahr" gesetzt ist?.', 'mp' ); ?></span></span> Pro Seite</th>
				<td>
					<input type="text" name="per_page" data-default="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welches Feld, um Produkte zu bestellen.', 'mp' ); ?></span></span> Sortieren nach</th>
				<td>
					<select name="order_by" data-default="<?php echo esc_attr( mp_get_setting( 'order_by' ) ); ?>">
						<?php
						$data = array(
							'title'	 => __( 'Produktname', 'mp' ),
							'date'	 => __( 'Veröffentlichung', 'mp' ),
							'ID'	 => __( 'Produkt ID', 'mp' ),
							'author' => __( 'Produktautor', 'mp' ),
							'sales'	 => __( 'Anzahl Verkäufe', 'mp' ),
							'price'	 => __( 'Produktpreis', 'mp' ),
							'rand'	 => __( 'Zufällig', 'mp' ),
						);

						foreach ( $data as $value => $label ) :
							?>
							<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, mp_get_setting( 'order_by' ) ); ?>><?php echo $label; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Bestellanweisung für Produkte von.', 'mp' ); ?></span></span> Sortieren</th>
				<td>
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="ASC" <?php checked( 'ASC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Aufsteigend', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="DESC" <?php checked( 'DESC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Absteigend', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Beschränkt die Liste auf eine bestimmte Produktkategorie.', 'mp' ); ?></span></span> Kategorie</th>
				<td>
					<select name="category" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_cats as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Beschränkt die Liste auf ein bestimmtes Produkt-Tag.', 'mp' ); ?></span></span> Schlagwort</th>
				<td>
					<select name="tag" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_tags as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Produkte werden als Liste oder Raster angezeigt.', 'mp' ); ?></span></span> Listenansicht</th>
				<td>
					<select name="list_view" data-default="" class="mp-chosen-select">
						<option value="1" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '1' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Liste', 'mp' ); ?></option>
						<option value="0" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '0' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Raster', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob die Produktfilter angezeigt werden sollen.', 'mp' ); ?></span></span> Filter</th>
				<td>
					<label><input type="radio" name="filters" data-default="<?php echo esc_attr( mp_get_setting( 'show_filters' ) ); ?>" value="1" <?php checked( '1', mp_get_setting( 'show_filters' ) ); ?> /> <?php _e( 'Zeigen', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="filters" data-default="<?php echo esc_attr( mp_get_setting( 'show_filters' ) ); ?>" value="0" <?php checked( '1', mp_get_setting( 'show_filters' ) ); ?> /> <?php _e( 'Verbergen', 'mp' ); ?></label>
				</td>
			</tr>
		</table>
		<?php
	}


	/**
	 * Displays the [mp_popular_products] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_popular_products_attributes() {
		?>
		<table id="mp-popular-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die maximale Anzahl der anzuzeigenden Produkt', 'mp' ); ?></span></span> Anzahl</th>
				<td>
					<input type="text" name="number" data-default="5" value="5" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_related_products] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_related_products_attributes() {
		?>
		<table id="mp-related-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Das Produkt, für das verwandte Produkte angezeigt werden sollen.', 'mp' ); ?></span></span> Produkt ID</th>
				<td>
					<input type="text" class="mp-select-product" name="product_id" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie Produkte in Beziehung gesetzt werden', 'mp' ); ?></span></span> Beziehen durch</th>
				<td>
					<select name="relate_by" data-default="<?php echo esc_attr( mp_get_setting( 'related_products->relate_by' ) ); ?>">
						<?php
						$data = array(
							'both'		 => __( 'Kategorie &amp; Tags', 'mp' ),
							'category'	 => __( 'Kategorie', 'mp' ),
							'tags'		 => __( 'Tags', 'mp' ),
						);

						foreach ( $data as $value => $label ) :
							?>
							<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, mp_get_setting( 'related_products->relate_by' ) ); ?>><?php echo $label; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele verwandte Elemente sollen angezeigt werden?.', 'mp' ); ?></span></span> Begrenzen</th>
				<td>
					<input type="text" name="limit" data-default="<?php echo esc_attr( mp_get_setting( 'related_products->show_limit' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'related_products->show_limit' ) ); ?>" />
				</td>
			</tr>
			<!--<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php /*_e( 'Whether to display the items as a simple list or based on the list/grid view setting.', 'mp' ); */?></span></span> simple_list</th>
				<td>
					<input type="checkbox" name="simple_list" data-default="<?php /*echo esc_attr( mp_get_setting( 'related_products->simple_list' ) ); */?>" <?php /*checked( 1, mp_get_setting( 'related_products->simple_list' ) ); */?> />
				</td>
			</tr>-->
		</table>
		<?php
	}

	/**
	 * Displays the [mp_list_products] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_list_products_attributes() {
		?>
		<table id="mp-list-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob die Produktliste paginiert werden soll. Dies ist nützlich, um nur eine Teilmenge anzuzeigen.', 'mp' ); ?></span></span>  Paginieren</th>
				<td>
					<input type="checkbox" name="paginate" data-default="<?php echo esc_attr( mp_get_setting( 'paginate' ) ); ?>" value="1" <?php checked( 1, mp_get_setting( 'paginate' ) ); ?> />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Seitenzahl, die in der Produktliste angezeigt werden soll, wenn "paginieren" auf "true" gesetzt ist.', 'mp' ); ?></span></span>  Seite</th>
				<td>
					<input type="text" name="page" data-default="1" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele Produkte sollen in der Produktliste angezeigt werden, wenn "paginieren" auf "wahr" gesetzt ist?.', 'mp' ); ?></span></span>  Pro Seite</th>
				<td>
					<input type="text" name="per_page" data-default="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welches Feld, um Produkte zu bestellen.', 'mp' ); ?></span></span> Sortieren nach</th>
				<td>
					<select name="order_by" data-default="<?php echo esc_attr( mp_get_setting( 'order_by' ) ); ?>">
						<?php
						$data = array(
							'title'	 => __( 'Produktname', 'mp' ),
							'date'	 => __( 'Veröffentlichung', 'mp' ),
							'ID'	 => __( 'Produkt ID', 'mp' ),
							'author' => __( 'Produktkategorie', 'mp' ),
							'sales'	 => __( 'Verkäufe', 'mp' ),
							'price'	 => __( 'Produktpreis', 'mp' ),
							'rand'	 => __( 'Zufällig', 'mp' ),
						);

						foreach ( $data as $value => $label ) :
							?>
							<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, mp_get_setting( 'order_by' ) ); ?>><?php echo $label; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Bestellanweisung für Produkte von.', 'mp' ); ?></span></span> Sortieren</th>
				<td>
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="ASC" <?php checked( 'ASC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Aufsteigend', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="DESC" <?php checked( 'DESC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Absteigend', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Beschränkt die Liste auf eine bestimmte Produktkategorie.', 'mp' ); ?></span></span> Kategorie</th>
				<td>
					<select name="category" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_cats as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Beschränkt die Liste auf ein bestimmtes Produkt-Tag.', 'mp' ); ?></span></span> Schlagwort</th>
				<td>
					<select name="tag" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_tags as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Produkte werden als Liste oder Raster angezeigt.', 'mp' ); ?></span></span> Listenansicht</th>
				<td>
					<select name="list_view" data-default="" class="mp-chosen-select">
						<option value="1" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '1' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Liste', 'mp' ); ?></option>
						<option value="0" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '0' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Raster', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob die Produktfilter angezeigt werden sollen.', 'mp' ); ?></span></span> Filter</th>
				<td>
					<label><input type="radio" name="filters" data-default="<?php echo esc_attr( mp_get_setting( 'show_filters' ) ); ?>" value="1" <?php checked( '1', mp_get_setting( 'show_filters' ) ); ?> /> <?php _e( 'Zeigen', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="filters" data-default="<?php echo esc_attr( mp_get_setting( 'show_filters' ) ); ?>" value="0" <?php checked( '1', mp_get_setting( 'show_filters' ) ); ?> /> <?php _e( 'Verbergen', 'mp' ); ?></label>
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_product_attributes() {
		?>
		<table id="mp-product-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des anzuzeigenden Produktes.', 'mp' ); ?></span></span> Produkt ID</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob der Produkttitel angezeigt werden soll.', 'mp' ); ?></span></span> Titel</th>
				<td>
					<input type="checkbox" name="title" data-default="0" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob und welche Art von Inhalt angezeigt werden soll.', 'mp' ); ?></span></span> content</th>
				<td>
					<select name="content" data-default="full">
						<option value="0"><?php _e( 'Nichts', 'mp' ); ?></option>
						<option value="excerpt"><?php _e( 'Auszug', 'mp' ); ?></option>
						<option value="full" selected><?php _e( 'Voll', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ob und welcher Kontext der Bildgröße angezeigt werden soll.', 'mp' ); ?></span></span> image</th>
				<td>
					<select name="image" data-default="single">
						<option value="0"><?php _e( 'Keine', 'mp' ); ?></option>
						<option value="single" selected><?php _e( 'Einzeln', 'mp' ); ?></option>
						<option value="list"><?php _e( 'Liste', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob das Produkt-Meta angezeigt werden soll (z. B. Preis, Schaltfläche "Kaufen")..', 'mp' ); ?></span></span> meta</th>
				<td>
					<input type="checkbox" name="meta" data-default="0" value="1" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product_image] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_product_image_attributes() {
		?>
		<table id="mp-product-image-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produktes.', 'mp' ); ?></span></span> Produkt ID</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welcher Kontext für voreingestellte Größenoptionen.', 'mp' ); ?></span></span> Kontext</th>
				<td>
					<select name="context" data-default="single">
						<option value="single" selected><?php _e( 'Einzeln', 'mp' ); ?></option>
						<option value="list"><?php _e( 'Liste', 'mp' ); ?></option>
						<option value="widget"><?php _e( 'Widget', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Stelle eine benutzerdefinierte Pixelbreite/-höhe ein. Wenn nicht angegeben, wird standardmäßig die durch "Kontext" festgelegte Größe verwendet.', 'mp' ); ?></span></span> size</th>
				<td>
					<input type="text" name="size" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Stelle die Ausrichtung des Bildes ein.', 'mp' ); ?></span></span> align</th>
				<td>
					<label><input type="radio" name="align" data-default="<?php echo esc_attr( mp_get_setting( 'image_alignment_single' ) ); ?>" value="alignnone" <?php checked( 'alignnone', mp_get_setting( 'image_alignment_single' ) ); ?> /> <?php _e( 'Nichts', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="align" data-default="<?php echo esc_attr( mp_get_setting( 'image_alignment_single' ) ); ?>" value="alignleft" <?php checked( 'alignleft', mp_get_setting( 'image_alignment_single' ) ); ?> /> <?php _e( 'Links', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="align" data-default="<?php echo esc_attr( mp_get_setting( 'image_alignment_single' ) ); ?>" value="alignright" <?php checked( 'alignright', mp_get_setting( 'image_alignment_single' ) ); ?> /> <?php _e( 'Rechts', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="align" data-default="<?php echo esc_attr( mp_get_setting( 'image_alignment_single' ) ); ?>" value="aligncenter" <?php checked( 'aligncenter', mp_get_setting( 'image_alignment_single' ) ); ?> /> <?php _e( 'Mittig', 'mp' ); ?></label> &nbsp; &nbsp;
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_buy_button] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_buy_button_attributes() {
		?>
		<table id="mp-buy-button-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produktes.', 'mp' ); ?></span></span> Produkt ID</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welcher Kontext für die Anzeige.', 'mp' ); ?></span></span> Kontext</th>
				<td>
					<label><input type="radio" value="single" name="context" data-default="single" value="single" checked> <?php _e( 'Einzeln', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" value="list" name="context" data-default="single" value="list"> <?php _e( 'Liste', 'mp' ); ?></label>
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product_price] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_product_price_attributes() {
		?>
		<table id="mp-product-price-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produktes.', 'mp' ); ?></span></span> Produkt ID</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<!--<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ein Etikett, das dem Preis vorangestellt wird.', 'mp' ); ?></span></span> label</th>
				<td>
					<input type="text" name="label" data-default="Price:" value="Price:" />
				</td>
			</tr>-->
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product_sku] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_product_sku_attributes() {
		?>
		<table id="mp-product-sku-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produktes.', 'mp' ); ?></span></span> Produkt ID</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product_stock] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_product_stock_attributes() {
		?>
		<table id="mp-product-stock-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produktes.', 'mp' ); ?></span></span> Produkt ID</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_product_meta] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_product_meta_attributes() {
		?>
		<table id="mp-product-meta-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die ID des Produktes.', 'mp' ); ?></span></span> Produkt ID</th>
				<td>
					<input type="text" name="product_id" data-default="" class="mp-select-product" />
				</td>
			</tr>
			<!--<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Ein Etikett, das dem Preis vorangestellt wird.', 'mp' ); ?></span></span> label</th>
				<td>
					<input type="text" name="label" data-default="Price:" value="Price:" />
				</td>
			</tr>-->
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welcher Kontext für die Anzeige.', 'mp' ); ?></span></span> Kontext</th>
				<td>
					<label><input type="radio" value="single" name="context" data-default="single" value="single" checked> <?php _e( 'Einzeln', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" value="list" name="context" data-default="single" value="list"> <?php _e( 'Liste', 'mp' ); ?></label>
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_cart_widget] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_cart_widget_attributes() {
		?>
		<table id="mp-cart-widget-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Titel des Warenkorbs.', 'mp' ); ?></span></span> Titel</th>
				<td>
					<input type="text" name="title" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text wird vor dem Warenkorb angezeigt.', 'mp' ); ?></span></span> Benutzerdefinierter Text</th>
				<td>
					<input type="text" name="custom_text" data-default="" value="" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob das Produktbild ein- oder ausgeblendet werden soll.', 'mp' ); ?></span></span> Produktbild anzeigen</th>
				<td>
					<input type="checkbox" name="show_product_image" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob die Produktmenge ein- oder ausgeblendet werden soll.', 'mp' ); ?></span></span> Produktmenge anzeigen</th>
				<td>
					<input type="checkbox" name="show_product_qty" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob der Produktpreis angezeigt oder ausgeblendet werden soll.', 'mp' ); ?></span></span> Produktpreis anzeigen</th>
				<td>
					<input type="checkbox" name="show_product_price" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob der Warenkorb nur auf Shopseiten angezeigt werden soll oder nicht.', 'mp' ); ?></span></span> Nur Shop-Seiten</th>
				<td>
					<input type="checkbox" name="only_store_pages" value="1" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_cart_link] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_cart_link_attributes() {
		?>
		<table id="mp-cart-link-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob ein anklickbarer Link oder eine URL zurückgegeben werden soll.', 'mp' ); ?></span></span> URL</th>
				<td>
					<input type="checkbox" name="url" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text, der im Link angezeigt werden soll.', 'mp' ); ?></span></span> Linktext</th>
				<td>
					<input type="text" name="link_text" data-default="" value="" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_store_link] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_store_link_attributes() {
		?>
		<table id="mp-store-link-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob ein anklickbarer Link oder eine URL zurückgegeben werden soll.', 'mp' ); ?></span></span> URL</th>
				<td>
					<input type="checkbox" name="url" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text, der im Link angezeigt werden soll.', 'mp' ); ?></span></span> Linktext</th>
				<td>
					<input type="text" name="link_text" data-default="" value="" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_products_link] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_products_link_attributes() {
		?>
		<table id="mp-products-link-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob ein anklickbarer Link oder eine URL zurückgegeben werden soll.', 'mp' ); ?></span></span> URL</th>
				<td>
					<input type="checkbox" name="url" data-default="1" value="1" checked />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Der Text, der im Link angezeigt werden soll.', 'mp' ); ?></span></span> Linktext</th>
				<td>
					<input type="text" name="link_text" data-default="" value="" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_list_global_products] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_list_global_products_attributes() {
		?>
		<table id="mp-list-global-products-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Gibt an, ob die Produktliste paginiert werden soll. Dies ist nützlich, um nur eine Teilmenge anzuzeigen.', 'mp' ); ?></span></span>  Paginieren</th>
				<td>
					<input type="checkbox" name="paginate" data-default="<?php echo esc_attr( mp_get_setting( 'paginate' ) ); ?>" value="1" <?php checked( 1, mp_get_setting( 'paginate' ) ); ?> />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Die Seitenzahl, die in der Produktliste angezeigt werden soll, wenn "paginieren" auf "true" gesetzt ist.', 'mp' ); ?></span></span>  Seite</th>
				<td>
					<input type="text" name="page" data-default="1" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele Produkte sollen in der Produktliste angezeigt werden, wenn "paginieren" auf "wahr" gesetzt ist.', 'mp' ); ?></span></span>  Pro Seite</th>
				<td>
					<input type="text" name="per_page" data-default="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'per_page' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Wie viele Produkte sollen in der Produktliste angezeigt werden, wenn "paginieren" auf "falsch" gesetzt ist?.', 'mp' ); ?></span></span> Begrenzen</th>
				<td>
					<input type="text" name="limit" data-default="<?php echo esc_attr( mp_get_setting( 'limit' ) ); ?>" value="<?php echo esc_attr( mp_get_setting( 'limit' ) ); ?>" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Welches Feld, um Produkte zu bestellen.', 'mp' ); ?></span></span> Sortieren nach</th>
				<td>
					<select name="order_by" data-default="<?php echo esc_attr( mp_get_setting( 'order_by' ) ); ?>">
						<?php
						$data = array(
							'title'	 => __( 'Produktname', 'mp' ),
							'date'	 => __( 'Veröffentlichung', 'mp' ),
							'ID'	 => __( 'Produkt ID', 'mp' ),
							'author' => __( 'Produktautor', 'mp' ),
							'sales'	 => __( 'Verkäufe', 'mp' ),
							'price'	 => __( 'Produktpreis', 'mp' ),
							'rand'	 => __( 'Zufällig', 'mp' ),
						);

						foreach ( $data as $value => $label ) :
							?>
							<option value="<?php echo esc_attr( $value ); ?>" <?php selected( $value, mp_get_setting( 'order_by' ) ); ?>><?php echo $label; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Bestellanweisung für Produkten von.', 'mp' ); ?></span></span> Sortieren</th>
				<td>
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="ASC" <?php checked( 'ASC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Aufsteigend', 'mp' ); ?></label> &nbsp; &nbsp;
					<label><input type="radio" name="order" data-default="<?php echo esc_attr( mp_get_setting( 'order' ) ); ?>" value="DESC" <?php checked( 'DESC', mp_get_setting( 'order' ) ); ?> /> <?php _e( 'Absteigend', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Beschränkt die Liste auf eine bestimmte Produktkategorie.', 'mp' ); ?></span></span> Kategorie</th>
				<td>
					<select name="category" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_cats as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Beschränkt die Liste auf ein bestimmtes Produkt-Tag.', 'mp' ); ?></span></span> Schlagwort</th>
				<td>
					<select name="tag" data-default="" class="mp-chosen-select">
						<option value=""><?php _e( 'Keine', 'mp' ); ?></option>
						<?php foreach ( $this->_product_tags as $term ) : ?>
							<option value="<?php echo esc_attr( isset( $term->slug ) ? $term->slug : ''  ); ?>"><?php echo isset( $term->name ) ? $term->name : ''; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Produkte werden als Liste oder Raster angezeigt.', 'mp' ); ?></span></span> Listenansicht</th>
				<td>
					<select name="list_view" data-default="" class="mp-chosen-select">
						<option value="1" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '1' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Liste', 'mp' ); ?></option>
						<option value="0" <?php echo esc_attr( ( mp_get_setting( 'list_view' ) == '0' ) ? 'selected="selected"' : ''  ); ?>><?php _e( 'Raster', 'mp' ); ?></option>
					</select>
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_global_categories_list] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_global_categories_list_attributes() {
		?>
		<table id="mp-global-categories-list-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortiere Kategorien alphabetisch, nach eindeutiger Kategorie-ID oder nach der Anzahl der Beiträge in dieser Kategorie.', 'mp' ); ?></span></span> Sortieren nach</th>
				<td>
					<select name="orderby" data-default="name">
						<?php foreach ( array( 'ID', 'name', 'slug', 'count', 'term_group' ) as $value ) : ?>
							<option <?php selected( $value, 'name' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge für Kategorien (entweder aufsteigend oder absteigend).', 'mp' ); ?></span></span> Sortieren</th>
				<td>
					<select name="order" data-default="ASC">
						<?php foreach ( array( 'ASC', 'DESC' ) as $value ) : ?>
							<option <?php selected( $value, 'ASC' ); ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Schaltet die Anzeige der aktuellen Anzahl von Posts in jeder Kategorie um.', 'mp' ); ?></span></span> Anzahl anzeigen</th>
				<td>
					<input type="checkbox" name="show_count" data-default="" value="1" />
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt die Anzahl der anzuzeigenden Kategorien fest. Dadurch wird der SQL LIMIT-Wert definiert.', 'mp' ); ?></span></span> Anzahl</th>
				<td>
					<input type="text" name="limit" data-default="" value="" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the [mp_global_categories_list] short code attributes
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_mp_global_tag_cloud_attributes() {
		?>
		<table id="mp-global-tag-cloud-shortcode" class="form-table" style="display:none">
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Reihenfolge der Tags.', 'mp' ); ?></span></span> Sortieren nach</th>
				<td>
					<label for="mp-tag-cloud-orderby-name"><input type="radio" name="orderby" id="mp-tag-cloud-orderby-name" data-default="name" value="name" checked /> <?php _e( 'Name', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-orderby-count"><input type="radio" name="orderby" id="mp-tag-cloud-orderby-count" data-default="count" value="count" /> <?php _e( 'Anzahl', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Sortierreihenfolge.', 'mp' ); ?></span></span> Sortieren</th>
				<td>
					<label for="mp-tag-cloud-order-asc"><input type="radio" name="order" id="mp-tag-cloud-order-asc" data-default="ASC" value="ASC" checked /> <?php _e( 'Aufsteigend', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-order-desc"><input type="radio" name="order" id="mp-tag-cloud-order-desc" data-default="ASC" value="DESC" /> <?php _e( 'Absteigend', 'mp' ); ?></label><br />
					<label for="mp-tag-cloud-order-rand"><input type="radio" name="order" id="mp-tag-cloud-order-rand" data-default="RAND" value="RAND" /> <?php _e( 'Zufällig', 'mp' ); ?></label>
				</td>
			</tr>
			<tr>
				<th scope="row"><span class="mp-tooltip dashicons dashicons-editor-help"><span><?php _e( 'Legt die Anzahl der anzuzeigenden Tags fest. Dadurch wird der SQL LIMIT-Wert definiert.', 'mp' ); ?></span></span> Anzahl</th>
				<td>
					<input type="text" name="limit" data-default="" value="" />
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Displays the short code builder submit/reset buttons
	 *
	 * @since 3.0
	 * @access public
	 */
	public function display_shortcode_builder_form_buttons() {
		?>
		<p class="submit">
			<input class="button-primary" type="submit" value="<?php _e( 'Shortcodes einfügen', 'mp' ); ?>" />
			<!--<input class="button" type="button" value="<?php _e( 'Auf Standard zurücksetzen', 'mp' ); ?>" />-->
		</p>
		<?php
	}

	/**
	 * Enqueues admin javascript/css
	 *
	 * @since 3.0
	 * @access public
	 */
	public function enqueue_styles_scripts() {
		if ( isset( $_GET['page'] ) ) {
			$page = $_GET['page'];
		} else {
			$page = '';
		}

		$screenpage = get_current_screen();

		// We have to refactor this to accept all post types

		if ( $page == 'shop-einstellungen'
			|| $page == 'shop-einstellungen-presentation'
			|| $page == 'shop-einstellungen-notifications'
			|| $page == 'shop-einstellungen-shipping'
			|| $page == 'shop-einstellungen-payments'
			|| $page == 'shop-einstellungen-productattributes'
			|| $page == 'shop-einstellungen-capabilities'
			|| $page == 'shop-einstellungen-addons'
			|| ( isset( $_GET['taxonomy'] ) && ($_GET['taxonomy'] == 'product_category' || $_GET['taxonomy'] == 'product_tag') )
			|| ( isset( $_GET['post_type'] ) && ($_GET['post_type'] == 'mp_coupon' || $_GET['post_type'] == 'mp_order' || $_GET['post_type'] == 'product' || $_GET['post_type'] == 'page') )
			|| ( isset( $screenpage->post_type ) && ( $screenpage->post_type == "product" || $screenpage->post_type == "incsub_event" || $screenpage->post_type == "post" || $screenpage->post_type == "mp_order" || $screenpage->post_type == "mp_coupon" || $screenpage->post_type == "page") ) )  {

			wp_enqueue_style( 'colorbox', mp_plugin_url( 'includes/admin/ui/colorbox/colorbox.css' ), false, MP_VERSION );
			wp_enqueue_script( 'colorbox', mp_plugin_url( 'ui/js/jquery.colorbox.js' ), false, MP_VERSION );

			wp_enqueue_style( 'mp-select2', mp_plugin_url( 'ui/select2/select2.css' ), false, MP_VERSION );
			wp_enqueue_script( 'mp-select2', mp_plugin_url( 'ui/select2/select2.js' ), false, MP_VERSION );

			wp_enqueue_script( 'mp-shortcode-builder', mp_plugin_url( 'includes/admin/ui/js/shortcode-builder.js', array( 'colorbox', 'chosen' ), MP_VERSION ) );
			wp_localize_script( 'mp-shortcode-builder', 'MP_ShortCode_Builder', array(
				'select_product' => __( 'Wähle ein Produkt', 'mp' ),
			) );

		}
	}

	/**
	 * Displays the short code builder button above the tinymce editor.
	 *
	 * @since 3.0
	 * @access public
	 */
	public function media_buttons( $editor_id ) {
		$sc_uilder = true;

		// We don't need to show this on addons page.
		if ( isset( $_REQUEST['page'] ) && $_REQUEST['page'] == 'shop-einstellungen-addons' ) {
			$sc_uilder = false;
		}

		/**
		 * Filter to disable or enable shortcode button.
		 *
		 * @param bool   $sc_uilder Enable or Disable.
		 * @param string $editor_id Current editor id.
		 *
		 * @since 3.2.10
		 */
		$sc_uilder = apply_filters( 'mp_media_buttons', $sc_uilder, $editor_id );

		// Show button only if enabled.
		if ( $sc_uilder ) {
			?>
			<a href="javascript:;" class="button mp-shortcode-builder-button" title="<?php _e( 'MarketPress-Shortcode hinzufügen', 'mp' ); ?>"><span class="wp-media-buttons-icon dashicons dashicons-cart"></span> <?php _e( 'MarketPress-Shortcode hinzufügen', 'mp' ); ?></a>
			<?php
		}
	}

}

MP_Shortcode_Builder::get_instance();